### ISSUE TITLE
worldborder command with installed WorldBorder plugin

### ISSUE THREAD

**Issue by RedstoneFuture** [pop4959/Chunky#224]
![grafik](https://user-images.githubusercontent.com/4140635/201140964-00c60d6d-421c-4ad6-95db-10e62f73003a.png)

![grafik](https://user-images.githubusercontent.com/4140635/201144726-673079e6-13fd-4c73-92d4-1cc3cb314b2d.png)

After I set the vanilla world border, the `/chunky worldborder` command sets the center to a wrong coordinate and the shape to circle, even though the vanilla world border can only be rectangular. I suggest updating the chunky-shape to `squared`.

1. `/worldborder center ~ ~`
2. `/worldborder set 5000`
3. optional: restart the server
4. `/chunky world world`
5. `/chunky worldborder`

---

Chunky v. `1.3.38`
ChunkyBorder v. `1.1.34`
PaperMC v. 1.19.2, `build 194`

**Comment by RedstoneFuture** [comment]
It looks like he used the (still installed) "WorldBorder" plugin. 

```
worlds:
  world:
    x: -285.05319047551217
    z: -148.64939510114144
    radiusX: 5000
    radiusZ: 5000
    wrapping: false
```

If "WorldBorder" manually overwrites the vanilla information, it's obviously not a mistake by Chunky.
![grafik](https://user-images.githubusercontent.com/4140635/201160749-c1000864-03be-40f2-ac34-0b17f272ec96.png)
